manifest_version = "0.1.0"

[project]
name = "backend"
type = "motoko"
main = "main.mo"

[build]
commands = ["bash ../../scripts/mopsw.sh install-with-retry", "bash ../../scripts/mopsw.sh build", "bash ../../scripts/run-bindgen.sh"]
out = "dist"

[check]
commands = ["bash ../../scripts/mopsw.sh check"]

[check.fix]
commands = ["bash ../../scripts/mopsw.sh check --fix"]
